import { brand } from '@/app/ui/theme';

export const ACCENT = brand.primary;
export const glass =
  'bg-white/75 backdrop-blur-2xl border border-black/10 shadow-[0_10px_30px_rgba(2,6,23,0.08)]';

export {
  GOOGLE_MAPS_API_KEY,
  QLD_BOUNDS,
  ROUTE_BASE_FEE,
  ROUTE_PER_KM_RATE,
  ROUTE_PER_MIN_RATE,
  ROUTE_MIN_PRICE,
  ROUTE_AVG_SPEED_KMH,
  ROUTE_SCOPES,
  WINDOW_PRICES,
  PRICE_OVERRIDE,
  SNEAKER_MULTI_PRICING,
  LAUNDRY_PER_LOAD_ADDONS,
  LAUNDRY_PER_ORDER_ADDONS,
  LAUNDRY_IRONING_PRICES,
  AUTO_SIZE_CATEGORIES,
  SNEAKER_TURNAROUND,
  SNEAKER_TURNAROUND_META,
  POLICY,
  SERVICE_REGIONS,
  ALLOWED_SERVICES_BY_CONTEXT,
  DEFAULT_DUMP_RUN,
  DEFAULT_DUMP_DELIVERY,
  DEFAULT_DUMP_TRANSPORT,
  WINDOWS_BASE_PER_STOREY_MIN,
  WIN_RULES,
  yardLabourRate,
} from '@/lib/services-core/constants';
