-- 112_growth_pipeline_p1.sql
-- Phase 1: Autonomous Growth Department pipeline wiring
-- Adds idempotency gates, scoring columns, traceability flags, and activity log.

-- ── story_opportunities ─────────────────────────────────────────────────────────
-- Gate: set true once a content_ideas row has been created from this opportunity.
-- Prevents duplicate ideas when the in_development transition fires more than once.
ALTER TABLE story_opportunities ADD COLUMN IF NOT EXISTS content_idea_created boolean NOT NULL DEFAULT false;

-- ── content_ideas ───────────────────────────────────────────────────────────────
-- Enforce one auto-created idea per opportunity at the DB level.
-- Manual ideas with no opportunity_id (NULL) are unaffected.
CREATE UNIQUE INDEX IF NOT EXISTS content_ideas_opportunity_id_unique
  ON content_ideas(opportunity_id)
  WHERE opportunity_id IS NOT NULL;

-- Idea scoring columns (pipeline step 4).
ALTER TABLE content_ideas ADD COLUMN IF NOT EXISTS idea_score   integer CHECK (idea_score BETWEEN 0 AND 100);
ALTER TABLE content_ideas ADD COLUMN IF NOT EXISTS score_breakdown jsonb;
ALTER TABLE content_ideas ADD COLUMN IF NOT EXISTS score_reason    text;
ALTER TABLE content_ideas ADD COLUMN IF NOT EXISTS scored_at       timestamptz;

-- ── content_scripts ─────────────────────────────────────────────────────────────
-- Traceability: was this script AI-generated by the pipeline or manually written?
ALTER TABLE content_scripts ADD COLUMN IF NOT EXISTS is_ai_generated  boolean NOT NULL DEFAULT false;
ALTER TABLE content_scripts ADD COLUMN IF NOT EXISTS generation_model text;

-- ── marketing_publishing_queue ──────────────────────────────────────────────────
-- Traceability: was this queue item auto-created by the pipeline?
ALTER TABLE marketing_publishing_queue ADD COLUMN IF NOT EXISTS auto_created boolean NOT NULL DEFAULT false;

-- ── growth_pipeline_events ──────────────────────────────────────────────────────
-- Lightweight activity log for all Growth Department pipeline automation events.
-- Separate from agent_runs — these are inline API-route side-effects, not agent runs.
CREATE TABLE IF NOT EXISTS growth_pipeline_events (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  -- What happened: opportunity_detected, opportunity_scored, idea_created,
  --                idea_scored, script_generated, queue_item_created
  event_type       text        NOT NULL,
  -- What triggered this event
  source_type      text,                                          -- 'journal_entry' | 'opportunity' | 'idea' | 'production_card'
  source_id        uuid,                                          -- FK-ish pointer to the source row (no hard constraint for flexibility)
  -- What was created or updated
  result_type      text,                                          -- 'story_opportunity' | 'content_idea' | 'content_script' | 'publishing_queue_item'
  result_id        uuid,
  -- Root trace back to the journal entry that started the chain
  journal_entry_id uuid        REFERENCES founder_journal_entries(id) ON DELETE SET NULL,
  -- Score, model, reason, skip reason, etc.
  metadata         jsonb,
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS growth_pipeline_events_source  ON growth_pipeline_events(source_id);
CREATE INDEX IF NOT EXISTS growth_pipeline_events_journal ON growth_pipeline_events(journal_entry_id);
CREATE INDEX IF NOT EXISTS growth_pipeline_events_time    ON growth_pipeline_events(created_at DESC);
CREATE INDEX IF NOT EXISTS growth_pipeline_events_type    ON growth_pipeline_events(event_type);
