/**
 * Obsidian note formatters for GitHub events.
 *
 * Each formatter returns:
 *   { title, body, tags, vaultPath }
 *
 * Body is markdown designed to render well in Obsidian — uses
 * callouts, tables, and [[wikilinks]] matching the existing Dev/
 * folder conventions.
 */

import type {
  ProcessedPR,
  ProcessedDeployment,
  ProcessedPush,
  ChangeClassification,
} from './types';

export interface FormattedNote {
  title: string;
  body: string;
  tags: string[];
  vaultPath: string;
  category: 'deployments' | 'bugs' | 'architecture' | 'design' | 'admin';
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 60);
}

function changeTypeBadge(c: ChangeClassification): string {
  const badges: Record<string, string> = {
    'feature':      '🟢 Feature',
    'bug-fix':      '🔴 Bug Fix',
    'architecture': '🏛️ Architecture',
    'database':     '🗄️ Database',
    'agent':        '🤖 Agent',
    'ui':           '🎨 UI',
    'config':       '⚙️ Config',
    'docs':         '📄 Docs',
    'chore':        '🔧 Chore',
    'breaking':     '💥 Breaking',
  };
  const parts = [badges[c.primary] ?? c.primary];
  if (c.isBreaking) parts.push('💥 Breaking Change');
  if (c.isArchitectural) parts.push('🏛️ Architectural');
  return parts.join('  ');
}

function systemsBlock(systems: string[]): string {
  if (systems.length === 0) return '';
  return `\n**Affected systems:** ${systems.map((s) => `\`${s}\``).join(', ')}`;
}

function backlinkRow(systems: string[]): string {
  return systems.map((s) => `[[${s}]]`).join('  ');
}

// ── PR note ───────────────────────────────────────────────────────────────────

export function formatPRNote(pr: ProcessedPR): FormattedNote {
  const date = today();
  const stateLabel = pr.state === 'merged' ? '✅ Merged' : pr.state === 'opened' ? '🔄 Open' : '❌ Closed';
  const diff = `+${pr.additions} / -${pr.deletions} across ${pr.changedFiles} files`;

  const body = [
    `---`,
    `type: pr`,
    `pr_number: ${pr.number}`,
    `repo: "${pr.repo}"`,
    `state: "${pr.state}"`,
    `author: "${pr.author}"`,
    `branch: "${pr.branch}"`,
    `base: "${pr.base}"`,
    `merged_at: ${pr.mergedAt ? `"${pr.mergedAt}"` : 'null'}`,
    `change_type: "${pr.classification.primary}"`,
    `is_breaking: ${pr.classification.isBreaking}`,
    `is_architectural: ${pr.classification.isArchitectural}`,
    `tags:`,
    `  - pr`,
    `  - ${pr.classification.primary}`,
    ...pr.classification.affectedSystems.map((s) => `  - ${s}`),
    `created: "${new Date().toISOString()}"`,
    `---`,
    '',
    `# PR #${pr.number}: ${pr.title}`,
    '',
    `**State:** ${stateLabel}  |  **Author:** ${pr.author}  |  **Diff:** ${diff}`,
    changeTypeBadge(pr.classification),
    systemsBlock(pr.classification.affectedSystems),
    '',
    `## Overview`,
    pr.body?.trim() ? pr.body.trim() : '_No description provided._',
    '',
    `## Stats`,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Branch | \`${pr.branch}\` → \`${pr.base}\` |`,
    `| Commits | ${pr.commits} |`,
    `| Lines added | ${pr.additions} |`,
    `| Lines deleted | ${pr.deletions} |`,
    `| Files changed | ${pr.changedFiles} |`,
    pr.labels.length > 0 ? `| Labels | ${pr.labels.join(', ')} |` : '',
    '',
    pr.mergeCommitSha
      ? `**Merge commit:** \`${pr.mergeCommitSha.slice(0, 7)}\``
      : '',
    '',
    `## Links`,
    `- [View PR on GitHub](${pr.url})`,
    '',
    ...(pr.classification.affectedSystems.length > 0
      ? [`## Backlinks`, backlinkRow(pr.classification.affectedSystems), '']
      : []),
    `*Auto-generated by github-historian on ${date}*`,
  ]
    .filter((l) => l !== null && l !== undefined)
    .join('\n');

  const category =
    pr.classification.primary === 'bug-fix'     ? 'bugs' :
    pr.classification.primary === 'architecture' ||
    pr.classification.primary === 'database'     ? 'architecture' :
    pr.classification.primary === 'ui'           ? 'design' :
    'deployments';

  return {
    title: `PR #${pr.number}: ${pr.title}`,
    body,
    tags: ['pr', pr.classification.primary, pr.repo, pr.state],
    vaultPath: `Dev/PRs/${date}-pr-${pr.number}-${slugify(pr.title)}.md`,
    category,
  };
}

// ── Deployment note ───────────────────────────────────────────────────────────

export function formatDeploymentNote(dep: ProcessedDeployment): FormattedNote {
  const date = today();
  const stateEmoji =
    dep.state === 'success'  ? '✅' :
    dep.state === 'failure'  ? '❌' :
    dep.state === 'error'    ? '🚨' :
    '⏳';

  const body = [
    `---`,
    `type: deployment`,
    `repo: "${dep.repo}"`,
    `environment: "${dep.environment}"`,
    `state: "${dep.state}"`,
    `sha: "${dep.sha}"`,
    `branch: "${dep.branch}"`,
    `tags:`,
    `  - deployment`,
    `  - ${dep.environment}`,
    `  - ${dep.state}`,
    `created: "${dep.timestamp}"`,
    `---`,
    '',
    `# Deployment: ${stateEmoji} ${dep.environment} — \`${dep.sha.slice(0, 7)}\``,
    '',
    `**State:** ${stateEmoji} ${dep.state.toUpperCase()}  |  **Environment:** ${dep.environment}  |  **Branch:** \`${dep.branch}\``,
    '',
    `## Details`,
    `| Field | Value |`,
    `|-------|-------|`,
    `| SHA | \`${dep.sha.slice(0, 7)}\` |`,
    `| Branch | \`${dep.branch}\` |`,
    `| Environment | ${dep.environment} |`,
    `| State | ${stateEmoji} ${dep.state} |`,
    dep.description ? `| Note | ${dep.description} |` : '',
    dep.durationMs ? `| Duration | ${(dep.durationMs / 1000).toFixed(1)}s |` : '',
    '',
    dep.url ? `## Deployment URL\n[${dep.url}](${dep.url})` : '',
    '',
    dep.state === 'failure' || dep.state === 'error'
      ? `> [!warning] Failed Deployment\n> Deployment to **${dep.environment}** failed at \`${dep.sha.slice(0, 7)}\`. Check Vercel logs.\n`
      : '',
    `## Rollback Reference`,
    dep.state === 'success'
      ? `Previous successful deployment SHA: see [[Dev/Deployments]] for history.`
      : `To rollback: trigger a revert of commit \`${dep.sha.slice(0, 7)}\` and redeploy.`,
    '',
    `*Auto-generated by github-historian on ${date}*`,
  ]
    .filter((l) => l !== null && l !== undefined)
    .join('\n');

  return {
    title: `Deployment: ${dep.environment} — ${dep.sha.slice(0, 7)} (${dep.state})`,
    body,
    tags: ['deployment', dep.environment, dep.state],
    vaultPath: `Dev/Deployments/${date}-deploy-${dep.environment}-${dep.sha.slice(0, 7)}.md`,
    category: 'deployments',
  };
}

// ── Push / implementation journal ─────────────────────────────────────────────

export function formatPushNote(push: ProcessedPush): FormattedNote {
  const date = today();
  const maxCommits = 8;
  const shown = push.commits.slice(0, maxCommits);
  const extra = push.commits.length - shown.length;

  const commitList = shown
    .map((c) => `- \`${c.id.slice(0, 7)}\` ${c.message.split('\n')[0].slice(0, 80)} — *${c.author.name}*`)
    .join('\n');

  const filesList =
    push.commits
      .flatMap((c) => [...c.added, ...c.modified, ...c.removed])
      .filter((v, i, a) => a.indexOf(v) === i)
      .slice(0, 20)
      .map((f) => `- \`${f}\``)
      .join('\n');

  const body = [
    `---`,
    `type: push`,
    `repo: "${push.repo}"`,
    `branch: "${push.branch}"`,
    `sha: "${push.sha}"`,
    `commit_count: ${push.commitCount}`,
    `change_type: "${push.classification.primary}"`,
    `is_architectural: ${push.classification.isArchitectural}`,
    `tags:`,
    `  - push`,
    `  - ${push.classification.primary}`,
    ...push.classification.affectedSystems.map((s) => `  - ${s}`),
    `created: "${push.timestamp}"`,
    `---`,
    '',
    `# Push to \`${push.branch}\` — ${push.commitCount} commit${push.commitCount !== 1 ? 's' : ''}`,
    '',
    `**Author:** ${push.author}  |  **SHA:** \`${push.sha.slice(0, 7)}\``,
    changeTypeBadge(push.classification),
    systemsBlock(push.classification.affectedSystems),
    '',
    `## Commits`,
    commitList,
    extra > 0 ? `_…and ${extra} more commits_` : '',
    '',
    filesList ? `## Files Changed\n${filesList}` : '',
    '',
    push.compareUrl ? `[View diff on GitHub](${push.compareUrl})` : '',
    '',
    ...(push.classification.isArchitectural
      ? [`> [!note] Architectural Change\n> This push touches architectural components. Consider whether an ADR update is needed → [[Dev/ADR-Index]]\n`]
      : []),
    ...(push.classification.primary === 'bug-fix'
      ? [`> [!success] Bug Fix\n> Mark the corresponding issue in [[Dev/Bug Tracker]] as resolved if applicable.\n`]
      : []),
    ...(push.classification.affectedSystems.length > 0
      ? [`## Backlinks`, backlinkRow(push.classification.affectedSystems), '']
      : []),
    `*Auto-generated by github-historian on ${date}*`,
  ]
    .filter((l) => l !== null && l !== undefined)
    .join('\n');

  const category =
    push.classification.primary === 'bug-fix'     ? 'bugs' :
    push.classification.primary === 'architecture' ||
    push.classification.primary === 'database'     ? 'architecture' :
    push.classification.primary === 'ui'           ? 'design' :
    'deployments';

  return {
    title: `Push: ${push.branch} — ${push.sha.slice(0, 7)} (${push.classification.primary})`,
    body,
    tags: ['push', push.classification.primary, push.branch],
    vaultPath: `Dev/Journal/${date}-push-${push.branch.replace(/\//g, '-')}-${push.sha.slice(0, 7)}.md`,
    category,
  };
}

// ── Release / changelog ───────────────────────────────────────────────────────

export interface FormattedRelease {
  tag: string;
  name: string;
  body: string;
  url: string;
  author: string;
  publishedAt: string;
  repo: string;
}

export function formatReleaseNote(release: FormattedRelease): FormattedNote {
  const date = today();
  const body = [
    `---`,
    `type: release`,
    `repo: "${release.repo}"`,
    `tag: "${release.tag}"`,
    `published_at: "${release.publishedAt}"`,
    `tags:`,
    `  - release`,
    `  - changelog`,
    `  - ${release.tag}`,
    `created: "${new Date().toISOString()}"`,
    `---`,
    '',
    `# Release ${release.tag}${release.name ? `: ${release.name}` : ''}`,
    '',
    `**Published by:** ${release.author}  |  **Date:** ${release.publishedAt.slice(0, 10)}`,
    '',
    `## Changelog`,
    release.body?.trim() || '_No release notes provided._',
    '',
    `## Links`,
    `- [View release on GitHub](${release.url})`,
    '',
    `## Architecture Impact`,
    `Review whether this release requires ADR updates → [[Dev/ADR-Index]]`,
    '',
    `*Auto-generated by github-historian on ${date}*`,
  ].join('\n');

  return {
    title: `Release ${release.tag}`,
    body,
    tags: ['release', 'changelog', release.tag],
    vaultPath: `Dev/Releases/${date}-release-${release.tag.replace(/[^a-z0-9.-]/gi, '-')}.md`,
    category: 'architecture',
  };
}
